### PR TITLE
Fix before_action filters in posts and links controller

### LINKED ISSUE #53: Fix before_action filters on links and posts controllers
This doesn't work:

> before_action :require_login, except: [:index, :show]
> before_action :require_login, only: [:show], if: '!post.published_at?'

It looks like the second conflicts with the first causing neither to be run. Or maybe the latter runs. Either way, needs to be sorted out.

## Desired behavior

- All actions in controller require login _except_ `index` and `show`.
- The `show` action should require login only if the page's resource is a draft (and thus hidden from non-authenticated users).

### PR DESCRIPTION
**Pull request by jgarber623**
This PR resolves #53.

### CODE REVIEW

File: app/controllers/francis_cms/links_controller.rb [hunk 1]
```diff
@@ -3,14 +3,13 @@
...
     before_action :require_login, except: [:index, :show]
-    before_action :require_login, only: [:show], if: '!link.published_at?'
 
     def index
       links
     end
 
     def show
-      link
+      require_login unless link.published_at?
```
Comment (jgarber623) [inline app/controllers/francis_cms/links_controller.rb]: `@link` (for the view) gets set when `link` is called in this line. Clever. Maybe _too_ clever.

This also applies to the `posts_controller.rb` below.
